# EN by Ssomar
# FR by AI
# ES by ?
# HU by ?
# ptBR (Brazil) by Seytani
# DE by N.T.G
# UK
# RU by AI
# ZH by AI
locale: EN
useMySQL: false
dbIP: 127.0.0.1
dbPort: 3306
dbName: myDB
dbUser: root
dbPassword: rootPassword
reduceDamageIndicatorWithProtolcolLib: false # if you have ProtocolLib installed, you can reduce the damage indicator amount (The amount of hearts that are displayed when you take damage)
silenceOutputs: # You can blacklist sentences that are sent to the console by The Ssomar plugins
  - "blacklist the sentence here"
globalSilenceOutputs: # You can blacklist sentences that are sent to the console by any plugin
  - "blacklist the sentence here"
disableCustomMetadataOnEntities: false # to disable the metadata fromSpawner and bowForce to be added to entities